serve:
  cookies:
    same_site_mode: Lax
  cors:
    enabled: true
    allowed_origins:
      - https://*.coldwire.org
urls:
  self:
    issuer: https://coldwire.org/
    public: https://auth.coldwire.org/
  consent: https://auth.coldwire.org/api/consent
  login: https://auth.coldwire.org/sign-in
  logout: https://auth.coldwire.org/api/logout
  post_logout_redirect: https://auth.coldwire.org/sign-in