## Server ##

server_name: "coldwire.org"

# When running as a daemon, the file to store the pid in
#
pid_file: /data/homeserver.pid

# The absolute URL to the web client which / will redirect to.
web_client_location: https://organize.coldwire.org/

listeners:
  - port: (| env "MATRIX_PORT" |)
    tls: false
    type: http
    x_forwarded: true

    resources:
      - names: [client, federation]
        compress: false

## Homeserver blocking ##

# How to reach the server admin, used in ResourceLimitError
admin_contact: 'mailto:contact@coldwire.org'

max_avatar_size: 5M

## Database ##

database:
  name: psycopg2
  args:
    user: synapse
    password: (| with secret "services/data/cw-matrix" |)(| .Data.data.db_password |)(| end |)
    database: synapse
    hostaddr: (| env "MATRIX_DB_ADDR" |)
    port: (| env "MATRIX_DB_PORT" |)
    cp_min: 5
    cp_max: 10


## Logging ##

# A yaml python logging config file as described by
# https://docs.python.org/3.7/library/logging.config.html#configuration-dictionary-schema
#
log_config: "/data/matrix.coldwire.org.log.config"


## Media Store ##

# Directory where uploaded images and attachments are stored.
media_store_path: "/data/media_store"

# The largest allowed upload size in bytes
max_upload_size: 50M

## Registration ##
#

enable_registration: false


auto_join_rooms:
  - "#home:matrix.coldwire.org"

# Whether the auto_join_rooms that are auto-created are available via
# federation. Only has an effect if autocreate_auto_join_rooms is true.
autocreate_auto_join_rooms_federated: false

## Metrics ###

report_stats: false

## API Configuration ##

# a secret which is used to sign access tokens. If none is specified,
# the registration_shared_secret is used, if one is given; otherwise,
# a secret key is derived from the signing key.
#
macaroon_secret_key: "(| with secret "services/data/cw-matrix" |)(| .Data.data.macaroon_secret_key |)(| end |)"

# a secret which is used to calculate HMACs for form values, to stop
# falsification of values. Must be specified for the User Consent
# forms to work.
#
form_secret: "(| with secret "services/data/cw-matrix" |)(| .Data.data.form_secret |)(| end |)"

## Signing Keys ##

# Path to the signing key to sign messages with
#
signing_key_path: "/data/matrix.coldwire.org.signing.key"


# Trusted key servers:
trusted_key_servers:
  - server_name: "matrix.org"

## Single sign-on integration ##

oidc_providers:
  # Coldwire
  - idp_id: coldwire
    idp_name: "Coldwire"
    discover: true
    issuer: "https://auth.coldwire.org/"
    client_id: "cw-matrix"
    client_secret: "(| with secret "services/data/cw-oidc-secrets" |)(| .Data.data.cw_matrix |)(| end |)"
    client_auth_method: client_secret_post
    scopes: ["openid"]
    skip_verification: false
    user_mapping_provider:
      config:
        localpart_template: "{{ user.username }}"
        display_name_template: "{{ user.username }}"

password_config:
   enabled: false